package com.example.technorides.greendaoexamplelol.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROGRAM".
 */
public class Program {

    private Long id;
    private String name;
    private java.util.Date beginDate;

    public Program() {
    }

    public Program(Long id) {
        this.id = id;
    }

    public Program(Long id, String name, java.util.Date beginDate) {
        this.id = id;
        this.name = name;
        this.beginDate = beginDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(java.util.Date beginDate) {
        this.beginDate = beginDate;
    }

}
